### PR TITLE
lockout after unsuccessful otp verification attempts

### PR DESCRIPTION
**Pull request by salehhashemi1992**
In this pull request, several enhancements and modifications were made to the OTP management system. The changes aim to improve OTP verification, handle verification attempts, and provide multilingual support for error messages.

Type: Enhancement
Description: Added a new configuration option in 'config/otp.php' to control the number of failed verification attempts allowed before OTP invalidation. This helps in improving security by limiting brute force attempts.

Type: Localization
Description: Added error messages in 'lang/en/otp.php' and 'lang/fa/otp.php' files to handle scenarios where verification attempts have exceeded the limit. This enhances user experience by providing appropriate feedback in English and Persian languages.

Type: Refactor
Description: Modified 'src/OtpManager.php' to include methods for handling verification attempts and resetting send attempts. These methods improve the OTP verification process by tracking failed attempts and resetting them on successful verification.

Type: Enhancement
Description: Altered the method of generating cache keys in 'src/OtpManager.php' to include OTP type, which can help in distinguishing between different types of OTPs.

Type: Tests
Description: Extended 'tests/OtpManagerTest.php' to include new test cases for verifying the functionality of exceeding maximum attempts and resetting attempts after successful verification. These tests ensure the robustness and reliability of the OTP manager system.

### CODE REVIEW

**Comment by salehhashemi1992** [comment]
**PR Auto Describe:**

Overall, the changes in this pull request are aimed at enhancing the security of the OTP system by introducing a rate limit for OTP verification attempts. This is to prevent brute force attacks by limiting the number of failed verification attempts allowed within a specific time frame.

1. **Type**: Refactor
   **Description**: Updated the `config/otp.php` file to include configurations for OTP verification rate limiting. These configurations allow setting the maximum number of verification attempts and the lockout time.

2. **Type**: Update
   **Description**: Updated the localization files in `lang/en/otp.php` and `lang/fa/otp.php` to include new messages related to OTP verification lockout and maximum attempts exceeded.

3. **Type**: Refactor
   **Description**: Modified the `src/OtpManager.php` file to implement the new rate limiting feature. This includes methods for checking if a mobile number is locked out due to too many failed verification attempts, handling a failed verification attempt, and resetting the number of attempts after a successful verification. The `send` and `verify` methods also now check for lockout before proceeding.

4. **Type**: Update
   **Description**: Updated the `tests/OtpManagerTest.php` file to include tests for the new rate limiting feature. This includes tests for OTP sending and verification during lockout, attempts reset after successful verification, lockout expiration, and lockout enforcement across different OTP types.

**Comment by salehhashemi1992** [comment]
**PR Auto Describe:**

The pull request includes changes mainly aimed at enhancing the OTP (One Time Password) functionality, adding a lockout feature for security enhancement, and improving internationalization through additional translations. 

1. **Type**: Feature Addition
   **Description**: Introduced lockout functionality to the OTP system. After a certain number of unsuccessful verification attempts, the user will be temporarily locked out.

2. **Type**: Feature Addition
   **Description**: Added a mechanism to handle verification attempts. If the maximum number of attempts is exceeded, the user will be locked out for a specified period.

3. **Type**: Feature Addition
   **Description**: Provided a feature to reset the verification attempts after a successful verification. This prevents users from getting locked out after successful verification.

4. **Type**: Refactor
   **Description**: Modified the 'send' and 'verify' methods to incorporate lockout checks before sending or verifying OTPs.

5. **Type**: Localization
   **Description**: Added new translation strings for the lockout messages in both English and Farsi.

6. **Type**: Code Optimization
   **Description**: Optimized the cache key generation in the 'getCacheKey' method by prefixing it with 'otp_'.

7. **Type**: Test Addition
   **Description**: Added several unit tests to verify the newly added lockout functionality, resetting of attempts after successful verification, and lockout enforcement across different OTP types.

**Comment by salehhashemi1992** [comment]
**PR Auto Describe:**

This pull request primarily introduces a new lockout mechanism for OTP verification attempts, along with corresponding updates to the language files and tests. 

1. **Type**: Feature
   **Description**: Added configuration options for OTP verification attempts and lockout duration in `config/otp.php`. This allows for control over how many failed verification attempts are allowed before a temporary lockout, and how long the lockout period lasts.

2. **Type**: Feature
   **Description**: Introduced new language strings in `lang/en/otp.php` and `lang/fa/otp.php` for lockout messages. These messages are displayed when a user is locked out due to multiple failed OTP verification attempts.

3. **Type**: Feature
   **Description**: Updated `src/OtpManager.php` to implement the lockout mechanism. This includes methods for checking for lockout, handling verification attempts, and resetting send attempts. The `send` and `verify` methods now also check for lockout before proceeding.

4. **Type**: Refactor
   **Description**: Changed the format of the cache key in `src/OtpManager.php` to include the prefix 'otp_'.

5. **Type**: Test
   **Description**: Added new tests in `tests/OtpManagerTest.php` to verify the lockout mechanism. These tests cover scenarios such as sending an OTP while locked out, resetting attempts after successful verification, lockout expiration, and lockout enforcement across different OTP types.

**Comment by salehhashemi1992** [comment]
**PR Auto Describe:**

In this pull request, several enhancements and modifications were made to the OTP management system. The changes aim to improve OTP verification, handle verification attempts, and provide multilingual support for error messages.

1. **Type**: Enhancement
   **Description**: Added a new configuration option in 'config/otp.php' to control the number of failed verification attempts allowed before OTP invalidation. This helps in improving security by limiting brute force attempts.

2. **Type**: Localization
   **Description**: Added error messages in 'lang/en/otp.php' and 'lang/fa/otp.php' files to handle scenarios where verification attempts have exceeded the limit. This enhances user experience by providing appropriate feedback in English and Persian languages.

3. **Type**: Refactor
   **Description**: Modified 'src/OtpManager.php' to include methods for handling verification attempts and resetting send attempts. These methods improve the OTP verification process by tracking failed attempts and resetting them on successful verification.

4. **Type**: Enhancement
   **Description**: Altered the method of generating cache keys in 'src/OtpManager.php' to include OTP type, which can help in distinguishing between different types of OTPs.

5. **Type**: Tests
   **Description**: Extended 'tests/OtpManagerTest.php' to include new test cases for verifying the functionality of exceeding maximum attempts and resetting attempts after successful verification. These tests ensure the robustness and reliability of the OTP manager system.

**Comment by salehhashemi1992** [comment]
@imahmood

**Review by imahmood — APPROVED** [review]

**Pull request merged**
